import { useState } from "react";
import { Brand } from "@/components/Brand";
import { Link } from "react-router-dom";
import { motion } from "framer-motion";
import { Button } from "@/components/ui/button";
import {
  Shield,
  Users,
  BarChart3,
  FileText,
  CheckCircle,
  AlertTriangle,
  Lock,
  ArrowRight,
  ChevronRight,
} from "lucide-react";
import { InstallAppButton } from "@/components/InstallAppButton";


const features = [
  {
    icon: Shield,
    title: "Culture Score Assessment",
    description: "Get a comprehensive 0-100 score measuring your organization's cybersecurity culture maturity.",
    color: "bg-[#18181B]",
  },
  {
    icon: Users,
    title: "Employee Surveys",
    description: "Easy-to-use surveys that measure awareness, behavior, and reporting culture across your team.",
    color: "bg-[#00A8E8]",
  },
  {
    icon: BarChart3,
    title: "Risk Visualization",
    description: "Interactive dashboards showing department-level risks and human vulnerability heatmaps.",
    color: "bg-[#2ECC71]",
  },
  {
    icon: FileText,
    title: "AI-Powered Reports",
    description: "Detailed audit reports with actionable recommendations generated by advanced AI analysis.",
    color: "bg-[#F39C12]",
  },
];

const steps = [
  { number: "01", title: "Register Your Company", description: "Create your account in minutes" },
  { number: "02", title: "Invite Employees", description: "Send survey links to your team" },
  { number: "03", title: "Collect Responses", description: "Employees complete the assessment" },
  { number: "04", title: "Get Your Report", description: "Receive AI-powered insights" },
];

const LandingPage = () => {
  return (
    <div className="min-h-screen bg-background">
      {/* Navigation */}
      <nav className="fixed top-0 left-0 right-0 z-50 bg-white/80 backdrop-blur-md border-b border-zinc-200">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 py-3 sm:py-4 flex flex-wrap items-center justify-between gap-3">
          <Link to="/" className="flex items-center gap-3 min-w-0 flex-shrink-0">
            <Brand size="md" />
          </Link>
          <div className="flex flex-wrap items-center justify-end gap-2 sm:gap-4 max-w-full">
            <InstallAppButton className="hidden md:inline-flex border-zinc-300 text-[#18181B] hover:bg-zinc-100" testId="nav-download-app-button" />
            <Link to="/pricing" data-testid="nav-pricing-link">
              <Button variant="ghost" className="px-2 sm:px-4 text-[#18181B] hover:text-[#00A8E8]">
                Pricing
              </Button>
            </Link>
            <Link to="/login">
              <Button variant="ghost" className="px-2 sm:px-4 text-[#18181B] hover:text-[#00A8E8]" data-testid="nav-login-btn">
                Login
              </Button>
            </Link>
            <Link to="/register">
              <Button className="bg-[#18181B] hover:bg-[#000000] text-white" data-testid="nav-register-btn">
                Get Started
              </Button>
            </Link>
          </div>
        </div>
      </nav>

      {/* Hero Section */}
      <section className="pt-32 pb-20 px-6 hero-gradient">
        <div className="max-w-7xl mx-auto">
          <div className="grid grid-cols-1 lg:grid-cols-2 gap-16 items-center">
            <motion.div
              initial={{ opacity: 0, x: -30 }}
              animate={{ opacity: 1, x: 0 }}
              transition={{ duration: 0.6 }}
            >
              <div className="inline-flex items-center gap-2 bg-[#00A8E8]/10 text-[#00A8E8] px-4 py-2 rounded-full text-sm font-medium mb-6">
                <Shield className="w-4 h-4" />
                Cybersecurity Culture Platform
              </div>
              <h1 className="text-4xl md:text-5xl lg:text-6xl font-bold text-[#18181B]  leading-tight mb-6">
                Measure & Strengthen Your{" "}
                <span className="text-[#00A8E8]">Cybersecurity Culture</span>
              </h1>
              <p className="text-lg text-zinc-600 mb-8 leading-relaxed max-w-xl">
                CultureShield AI helps SMBs assess employee cybersecurity awareness, identify human risks, and build a security-first culture with AI-powered insights.
              </p>
              <div className="flex flex-wrap gap-4">
                <Link to="/register">
                  <Button
                    size="lg"
                    className="bg-[#18181B] hover:bg-[#000000] text-white px-8 h-12 text-base"
                    data-testid="hero-cta-btn"
                  >
                    Start Free Assessment
                    <ArrowRight className="ml-2 w-5 h-5" />
                  </Button>
                </Link>
                <Link to="/login">
                  <Button
                    size="lg"
                    variant="outline"
                    className="border-2 border-[#18181B] text-[#18181B] hover:bg-[#18181B] hover:text-white px-8 h-12 text-base"
                    data-testid="hero-login-btn"
                  >
                    View Demo Dashboard
                  </Button>
                </Link>
                <Link to="/pricing">
                  <Button
                    size="lg"
                    variant="outline"
                    className="border-2 border-[#00A8E8] text-[#00A8E8] hover:bg-[#00A8E8] hover:text-white px-8 h-12 text-base"
                    data-testid="hero-pricing-btn"
                  >
                    Explore Pricing
                  </Button>
                </Link>
                <InstallAppButton
                  className="border-2 border-[#2ECC71] text-[#2ECC71] hover:bg-[#2ECC71] hover:text-white px-8 h-12 text-base"
                  size="lg"
                  testId="hero-download-app-button"
                />
              </div>
              <div className="flex items-center gap-8 mt-10">
                <div className="flex items-center gap-2">
                  <CheckCircle className="w-5 h-5 text-[#2ECC71]" />
                  <span className="text-sm text-zinc-600">No credit card required</span>
                </div>
                <div className="flex items-center gap-2">
                  <CheckCircle className="w-5 h-5 text-[#2ECC71]" />
                  <span className="text-sm text-zinc-600">5-minute setup</span>
                </div>
              </div>
            </motion.div>

            <motion.div
              initial={{ opacity: 0, x: 30 }}
              animate={{ opacity: 1, x: 0 }}
              transition={{ duration: 0.6, delay: 0.2 }}
              className="relative"
            >
              {/* Dashboard Preview */}
              <div className="bg-white rounded-2xl shadow-2xl border border-zinc-200 p-6 relative">
                <div className="absolute -top-3 -right-3 bg-[#2ECC71] text-white px-3 py-1 rounded-full text-xs font-semibold">
                  LIVE PREVIEW
                </div>
                <div className="flex items-center justify-between mb-6">
                  <h3 className="font-semibold text-[#18181B]">CultureShield Score</h3>
                  <span className="text-sm text-zinc-500">Last updated: Today</span>
                </div>
                <div className="flex items-center justify-center mb-6">
                  <div className="relative w-40 h-40">
                    <svg className="w-40 h-40 transform -rotate-90">
                      <circle
                        cx="80"
                        cy="80"
                        r="70"
                        stroke="#e2e8f0"
                        strokeWidth="12"
                        fill="none"
                      />
                      <circle
                        cx="80"
                        cy="80"
                        r="70"
                        stroke="#00A8E8"
                        strokeWidth="12"
                        fill="none"
                        strokeLinecap="round"
                        strokeDasharray={`${63 * 4.4} ${100 * 4.4}`}
                      />
                    </svg>
                    <div className="absolute inset-0 flex flex-col items-center justify-center">
                      <span className="text-4xl font-bold text-[#18181B]">63</span>
                      <span className="text-sm text-zinc-500">/ 100</span>
                    </div>
                  </div>
                </div>
                <div className="flex justify-center mb-6">
                  <span className="bg-[#F39C12]/10 text-[#F39C12] px-4 py-1 rounded-full text-sm font-semibold">
                    Medium Risk
                  </span>
                </div>
                <div className="grid grid-cols-3 gap-4">
                  <div className="text-center p-3 bg-zinc-50 rounded-lg">
                    <div className="text-2xl font-bold text-[#18181B]">72%</div>
                    <div className="text-xs text-zinc-500">Awareness</div>
                  </div>
                  <div className="text-center p-3 bg-zinc-50 rounded-lg">
                    <div className="text-2xl font-bold text-[#18181B]">58%</div>
                    <div className="text-xs text-zinc-500">Behavior</div>
                  </div>
                  <div className="text-center p-3 bg-zinc-50 rounded-lg">
                    <div className="text-2xl font-bold text-[#18181B]">61%</div>
                    <div className="text-xs text-zinc-500">Reporting</div>
                  </div>
                </div>
              </div>
            </motion.div>
          </div>
        </div>
      </section>

      {/* Features Section */}
      <section className="py-24 px-6 bg-white">
        <div className="max-w-7xl mx-auto">
          <motion.div
            initial={{ opacity: 0, y: 20 }}
            whileInView={{ opacity: 1, y: 0 }}
            viewport={{ once: true }}
            className="text-center mb-16"
          >
            <h2 className="text-3xl md:text-4xl font-bold text-[#18181B]  mb-4">
              Everything You Need to Assess Cyber Culture
            </h2>
            <p className="text-lg text-zinc-600 max-w-2xl mx-auto">
              Comprehensive tools to measure, analyze, and improve your organization's cybersecurity posture
            </p>
          </motion.div>

          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-8">
            {features.map((feature, index) => (
              <motion.div
                key={feature.title}
                initial={{ opacity: 0, y: 20 }}
                whileInView={{ opacity: 1, y: 0 }}
                viewport={{ once: true }}
                transition={{ delay: index * 0.1 }}
                className="feature-card group"
                data-testid={`feature-card-${index}`}
              >
                <div className={`feature-icon ${feature.color} text-white`}>
                  <feature.icon className="w-6 h-6" />
                </div>
                <h3 className="text-xl font-semibold text-[#18181B] mb-3 group-hover:text-[#00A8E8] transition-colors">
                  {feature.title}
                </h3>
                <p className="text-zinc-600 leading-relaxed">{feature.description}</p>
              </motion.div>
            ))}
          </div>
        </div>
      </section>

      {/* How It Works */}
      <section className="py-24 px-6 bg-zinc-50">
        <div className="max-w-7xl mx-auto">
          <motion.div
            initial={{ opacity: 0, y: 20 }}
            whileInView={{ opacity: 1, y: 0 }}
            viewport={{ once: true }}
            className="text-center mb-16"
          >
            <h2 className="text-3xl md:text-4xl font-bold text-[#18181B]  mb-4">
              How CultureShield Works
            </h2>
            <p className="text-lg text-zinc-600 max-w-2xl mx-auto">
              Get your cybersecurity culture assessment in four simple steps
            </p>
          </motion.div>

          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-8">
            {steps.map((step, index) => (
              <motion.div
                key={step.number}
                initial={{ opacity: 0, y: 20 }}
                whileInView={{ opacity: 1, y: 0 }}
                viewport={{ once: true }}
                transition={{ delay: index * 0.1 }}
                className="relative"
              >
                <div className="bg-white rounded-xl p-8 border border-zinc-200 hover:border-[#00A8E8] transition-colors">
                  <div className="text-5xl font-bold text-[#00A8E8]/20 mb-4 ">
                    {step.number}
                  </div>
                  <h3 className="text-xl font-semibold text-[#18181B] mb-2">{step.title}</h3>
                  <p className="text-zinc-600">{step.description}</p>
                </div>
                {index < steps.length - 1 && (
                  <ChevronRight className="hidden lg:block absolute top-1/2 -right-4 w-8 h-8 text-zinc-300 transform -translate-y-1/2" />
                )}
              </motion.div>
            ))}
          </div>
        </div>
      </section>

      {/* CTA Section */}
      <section className="py-24 px-6 bg-[#18181B]">
        <div className="max-w-4xl mx-auto text-center">
          <motion.div
            initial={{ opacity: 0, y: 20 }}
            whileInView={{ opacity: 1, y: 0 }}
            viewport={{ once: true }}
          >
            <div className="flex justify-center mb-6">
              <div className="bg-white/10 p-4 rounded-full">
                <Shield className="w-12 h-12 text-[#00A8E8]" />
              </div>
            </div>
            <h2 className="text-3xl md:text-4xl font-bold text-white  mb-4">
              Ready to Secure Your Organization's Culture?
            </h2>
            <p className="text-lg text-zinc-300 mb-8 max-w-2xl mx-auto">
              Join hundreds of companies using CultureShield to build security-aware teams and reduce human cyber risk.
            </p>
            <Link to="/register">
              <Button
                size="lg"
                className="bg-[#00A8E8] hover:bg-[#008dc2] text-white px-10 h-14 text-lg"
                data-testid="cta-btn"
              >
                Get Started Free
                <ArrowRight className="ml-2 w-5 h-5" />
              </Button>
            </Link>
          </motion.div>
        </div>
      </section>

      {/* Footer */}
      <footer className="py-12 px-6 bg-zinc-900 text-zinc-400">
        <div className="max-w-7xl mx-auto flex flex-col md:flex-row justify-between items-center gap-6">
          <div className="flex items-center gap-3">
            <Brand size="sm" />
            <span className="text-white font-semibold">CultureShield AI</span>
          </div>
          <p className="text-sm">
            © {new Date().getFullYear()} CultureShield. All rights reserved.
          </p>
          <div className="flex items-center gap-6">
            <Lock className="w-5 h-5" />
            <span className="text-sm">Enterprise-grade Security</span>
          </div>
        </div>
      </footer>
    </div>
  );
};

export default LandingPage;
